# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pyxart.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cpyxart.proto\"\x13\n\x04Ping\x12\x0b\n\x03msg\x18\x01 \x02(\t\"\x13\n\x04Pong\x12\x0b\n\x03msg\x18\x01 \x02(\t\"M\n\x12\x43lientRegistration\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x14\n\x0ciden_key_pub\x18\x02 \x02(\x0c\x12\x13\n\x0bpre_key_pub\x18\x03 \x02(\x0c\"\x07\n\x05\x45mpty\"\x1a\n\nClientName\x12\x0c\n\x04name\x18\x01 \x02(\t\"\x1c\n\rGroupCreation\x12\x0b\n\x03\x61rt\x18\x01 \x02(\x0c\"O\n\tGroupInfo\x12\x18\n\x04name\x18\x01 \x02(\x0b\x32\n.GroupName\x12(\n\x10\x63reation_message\x18\x02 \x02(\x0b\x32\x0e.GroupCreation\"\x13\n\x04Text\x12\x0b\n\x03msg\x18\x01 \x02(\x0c\"\x19\n\tGroupName\x12\x0c\n\x04name\x18\x01 \x02(\t\"8\n\x07Payload\x12\x19\n\x05group\x18\x01 \x02(\x0b\x32\n.GroupName\x12\x12\n\x03msg\x18\x02 \x02(\x0b\x32\x05.Text2\xb3\x02\n\x06Pyxart\x12\x16\n\x04ping\x12\x05.Ping\x1a\x05.Pong\"\x00\x12(\n\x08register\x12\x13.ClientRegistration\x1a\x05.Pong\"\x00\x12*\n\tget_users\x12\x06.Empty\x1a\x13.ClientRegistration0\x01\x12*\n\rget_my_groups\x12\x0b.ClientName\x1a\n.GroupInfo0\x01\x12,\n\x0c\x63reate_group\x12\x0e.GroupCreation\x1a\n.GroupName\"\x00\x12+\n\x16send_encrypted_message\x12\x08.Payload\x1a\x05.Pong\"\x00\x12\x34\n\x1bretrieve_encrypted_messages\x12\n.GroupName\x1a\x05.Text\"\x00\x30\x01')



_PING = DESCRIPTOR.message_types_by_name['Ping']
_PONG = DESCRIPTOR.message_types_by_name['Pong']
_CLIENTREGISTRATION = DESCRIPTOR.message_types_by_name['ClientRegistration']
_EMPTY = DESCRIPTOR.message_types_by_name['Empty']
_CLIENTNAME = DESCRIPTOR.message_types_by_name['ClientName']
_GROUPCREATION = DESCRIPTOR.message_types_by_name['GroupCreation']
_GROUPINFO = DESCRIPTOR.message_types_by_name['GroupInfo']
_TEXT = DESCRIPTOR.message_types_by_name['Text']
_GROUPNAME = DESCRIPTOR.message_types_by_name['GroupName']
_PAYLOAD = DESCRIPTOR.message_types_by_name['Payload']
Ping = _reflection.GeneratedProtocolMessageType('Ping', (_message.Message,), {
  'DESCRIPTOR' : _PING,
  '__module__' : 'pyxart_pb2'
  # @@protoc_insertion_point(class_scope:Ping)
  })
_sym_db.RegisterMessage(Ping)

Pong = _reflection.GeneratedProtocolMessageType('Pong', (_message.Message,), {
  'DESCRIPTOR' : _PONG,
  '__module__' : 'pyxart_pb2'
  # @@protoc_insertion_point(class_scope:Pong)
  })
_sym_db.RegisterMessage(Pong)

ClientRegistration = _reflection.GeneratedProtocolMessageType('ClientRegistration', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTREGISTRATION,
  '__module__' : 'pyxart_pb2'
  # @@protoc_insertion_point(class_scope:ClientRegistration)
  })
_sym_db.RegisterMessage(ClientRegistration)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'pyxart_pb2'
  # @@protoc_insertion_point(class_scope:Empty)
  })
_sym_db.RegisterMessage(Empty)

ClientName = _reflection.GeneratedProtocolMessageType('ClientName', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTNAME,
  '__module__' : 'pyxart_pb2'
  # @@protoc_insertion_point(class_scope:ClientName)
  })
_sym_db.RegisterMessage(ClientName)

GroupCreation = _reflection.GeneratedProtocolMessageType('GroupCreation', (_message.Message,), {
  'DESCRIPTOR' : _GROUPCREATION,
  '__module__' : 'pyxart_pb2'
  # @@protoc_insertion_point(class_scope:GroupCreation)
  })
_sym_db.RegisterMessage(GroupCreation)

GroupInfo = _reflection.GeneratedProtocolMessageType('GroupInfo', (_message.Message,), {
  'DESCRIPTOR' : _GROUPINFO,
  '__module__' : 'pyxart_pb2'
  # @@protoc_insertion_point(class_scope:GroupInfo)
  })
_sym_db.RegisterMessage(GroupInfo)

Text = _reflection.GeneratedProtocolMessageType('Text', (_message.Message,), {
  'DESCRIPTOR' : _TEXT,
  '__module__' : 'pyxart_pb2'
  # @@protoc_insertion_point(class_scope:Text)
  })
_sym_db.RegisterMessage(Text)

GroupName = _reflection.GeneratedProtocolMessageType('GroupName', (_message.Message,), {
  'DESCRIPTOR' : _GROUPNAME,
  '__module__' : 'pyxart_pb2'
  # @@protoc_insertion_point(class_scope:GroupName)
  })
_sym_db.RegisterMessage(GroupName)

Payload = _reflection.GeneratedProtocolMessageType('Payload', (_message.Message,), {
  'DESCRIPTOR' : _PAYLOAD,
  '__module__' : 'pyxart_pb2'
  # @@protoc_insertion_point(class_scope:Payload)
  })
_sym_db.RegisterMessage(Payload)

_PYXART = DESCRIPTOR.services_by_name['Pyxart']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PING._serialized_start=16
  _PING._serialized_end=35
  _PONG._serialized_start=37
  _PONG._serialized_end=56
  _CLIENTREGISTRATION._serialized_start=58
  _CLIENTREGISTRATION._serialized_end=135
  _EMPTY._serialized_start=137
  _EMPTY._serialized_end=144
  _CLIENTNAME._serialized_start=146
  _CLIENTNAME._serialized_end=172
  _GROUPCREATION._serialized_start=174
  _GROUPCREATION._serialized_end=202
  _GROUPINFO._serialized_start=204
  _GROUPINFO._serialized_end=283
  _TEXT._serialized_start=285
  _TEXT._serialized_end=304
  _GROUPNAME._serialized_start=306
  _GROUPNAME._serialized_end=331
  _PAYLOAD._serialized_start=333
  _PAYLOAD._serialized_end=389
  _PYXART._serialized_start=392
  _PYXART._serialized_end=699
# @@protoc_insertion_point(module_scope)
