# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pyxart.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cpyxart.proto\"\x13\n\x04Ping\x12\x0b\n\x03msg\x18\x01 \x02(\t\"\x13\n\x04Pong\x12\x0b\n\x03msg\x18\x01 \x02(\t\"M\n\x12\x43lientRegistration\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x14\n\x0ciden_key_pub\x18\x02 \x02(\x0c\x12\x13\n\x0bpre_key_pub\x18\x03 \x02(\x0c\"\x07\n\x05\x45mpty\"\x1a\n\nClientName\x12\x0c\n\x04name\x18\x01 \x02(\t\"\x1c\n\rGroupCreation\x12\x0b\n\x03\x61rt\x18\x01 \x02(\x0c\"O\n\tGroupInfo\x12\x18\n\x04name\x18\x01 \x02(\x0b\x32\n.GroupName\x12(\n\x10\x63reation_message\x18\x02 \x02(\x0b\x32\x0e.GroupCreation\"\x13\n\x04Text\x12\x0b\n\x03msg\x18\x01 \x02(\x0c\"\x19\n\tGroupName\x12\x0c\n\x04name\x18\x01 \x02(\t\"8\n\x07Payload\x12\x19\n\x05group\x18\x01 \x02(\x0b\x32\n.GroupName\x12\x12\n\x03msg\x18\x02 \x02(\x0b\x32\x05.Text2\xb3\x02\n\x06Pyxart\x12\x16\n\x04ping\x12\x05.Ping\x1a\x05.Pong\"\x00\x12(\n\x08register\x12\x13.ClientRegistration\x1a\x05.Pong\"\x00\x12*\n\tget_users\x12\x06.Empty\x1a\x13.ClientRegistration0\x01\x12*\n\rget_my_groups\x12\x0b.ClientName\x1a\n.GroupInfo0\x01\x12,\n\x0c\x63reate_group\x12\x0e.GroupCreation\x1a\n.GroupName\"\x00\x12+\n\x16send_encrypted_message\x12\x08.Payload\x1a\x05.Pong\"\x00\x12\x34\n\x1bretrieve_encrypted_messages\x12\n.GroupName\x1a\x05.Text\"\x00\x30\x01')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pyxart_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PING._serialized_start=16
  _PING._serialized_end=35
  _PONG._serialized_start=37
  _PONG._serialized_end=56
  _CLIENTREGISTRATION._serialized_start=58
  _CLIENTREGISTRATION._serialized_end=135
  _EMPTY._serialized_start=137
  _EMPTY._serialized_end=144
  _CLIENTNAME._serialized_start=146
  _CLIENTNAME._serialized_end=172
  _GROUPCREATION._serialized_start=174
  _GROUPCREATION._serialized_end=202
  _GROUPINFO._serialized_start=204
  _GROUPINFO._serialized_end=283
  _TEXT._serialized_start=285
  _TEXT._serialized_end=304
  _GROUPNAME._serialized_start=306
  _GROUPNAME._serialized_end=331
  _PAYLOAD._serialized_start=333
  _PAYLOAD._serialized_end=389
  _PYXART._serialized_start=392
  _PYXART._serialized_end=699
# @@protoc_insertion_point(module_scope)
